project_id = "yisadywqfexjspkbttrv"

[functions.create-razorpay-order]
verify_jwt = false

[functions.list-orders]
verify_jwt = true

[functions.send-order-whatsapp]
verify_jwt = false

[functions.send-whatsapp-otp]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.verify-whatsapp-otp]
verify_jwt = false

[functions.verify-msg91-widget]
verify_jwt = false
